# .github/workflows/terraform-deploy.yml

name: 'Terraform F5 Site Deployment'

on:
  push:
    branches:
      - main
    paths:
      - 'sites.tfvars'
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform Plan & Apply'
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }} 
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Decode .p12 Certificate
        run: |
          echo "Decoding F5 API certificate..."
          echo "${{ secrets.P12_FILE_BASE64 }}" | base64 --decode > creds.p12
        env:
          P12_FILE_BASE64: ${{ secrets.P12_FILE_BASE64 }}

      # This is the updated init step that configures the S3 backend
      - name: Terraform Init
        id: init
        run: |
          terraform init \
            -backend-config="bucket=f5-pipeline-demo-tfstate" \
            -backend-config="key=f5-sites/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}"

      - name: Terraform Plan
        id: plan
        env:
          VES_P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        run: terraform plan -out=tfplan -input=false -var-file="sites.tfvars"

      - name: Manual Approval Gate
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: "Adios-official"
          minimum-approvals: 1
          issue-title: "Deployment Approval Required for F5 Site"
          issue-body: "A new Terraform plan has been generated. Please review the plan output above and approve to apply the changes."
          
      - name: Terraform Apply
        id: apply
        env:
          VES_P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        run: terraform apply -auto-approve tfplan
