# .github/workflows/terraform-destroy.yml

name: 'Terraform Destroy F5 Site'

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "destroy" to confirm you want to permanently delete the infrastructure.'
        required: true

jobs:
  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    
    if: github.event.inputs.confirmation == 'destroy'

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }} 
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Decode .p12 Certificate
        run: |
          echo "${{ secrets.P12_FILE_BASE64 }}" | base64 --decode > creds.p12
        env:
          P12_FILE_BASE64: ${{ secrets.P12_FILE_BASE64 }}

      # UPDATED: Terraform Init now configures the S3 backend
      - name: Terraform Init
        id: init
        run: |
          terraform init \
            -backend-config="bucket=f5-pipeline-demo-tfstate" \
            -backend-config="key=f5-sites/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}"

      - name: Terraform Destroy
        id: destroy
        env:
          VES_P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        run: terraform destroy -auto-approve -var-file="sites.tfvars"
